### ISSUE TITLE
请问外接显示器正常吗？

### ISSUE THREAD

**Issue by konstant2016** [Mother-FKR/RazerBlade15-Base-Model-Hackintosh#10]
DP接口和HDMI接口走的独显直连，无解
但是雷电3接口，可以正常外接显示器吗？

**Comment by tyson-hu** [comment]
尽管雷电的口是一个可行的USB口，但是我认为通过拓展坞插显示器的成功性不大（我并没有直接尝试过）不过你也可以尝试一下displaylink之类的产品来连接显示器，它同样也需要一个USB的转接口来插显示器.

**Comment by konstant2016** [comment]
> 尽管雷电的口是一个可行的USB口，但是我认为通过拓展坞插显示器的成功性不大（我并没有直接尝试过）不过你也可以尝试一下displaylink之类的产品来连接显示器，它同样也需要一个USB的转接口来插显示器.

收到，非常感谢~
