### ISSUE TITLE
无法使用AMIBCP编辑BIOS

### ISSUE THREAD

**Issue by JialeDeng** [Mother-FKR/RazerBlade15-Base-Model-Hackintosh#11]
作者你好，非常感谢你的黑苹果教程。但在使用AMIBCP编辑提取出来的BIOS文件时，打开软件时出现了这样的报错，导致没有setup选项
![image](https://user-images.githubusercontent.com/55864517/123902724-edf1b400-d99f-11eb-8308-fca4af7d923b.png)
请问您知道是什么问题吗？我的BIOS信息如下：
![image](https://user-images.githubusercontent.com/55864517/123902790-095cbf00-d9a0-11eb-9ce9-f9e090a3b911.png)
电脑版本是灵刃15 2020 advanced，所用软件版本：AMIBCP 5.01.0014，AFUWINGUI 5.12.00.1904。十分感谢！

**Comment by tyson-hu** [comment]
你去试试我库里的AMIBCP(5.02.0031)吧，我看有人跟你遇到一样的[问题](http://forum.notebookreview.com/threads/razer-bios-mods-potential-to-unlock-all-hidden-options.830993/page-14)过，换个新版本的就好了.

**Comment by JialeDeng** [comment]
谢谢大佬帮助，已经可以编辑啦~~
