### ISSUE TITLE
Suggest change to MacBookPro15,2 SMBIOS

### ISSUE THREAD

**Issue by doanhxd** [Mother-FKR/RazerBlade15-Base-Model-Hackintosh#2]
I'm using my Razer Blade 15 Advanced model 2018 with SMBIOS MacbookPro15,2... When I try to use other SMBIOS except 15,2... the TB3(typeC) port not working anymore... When I plug the cable type-C to HDMI (to use my discrete display), it's not working unless change back to MBP15,2... I thought your problem with TB3 port is using another SMBIOS except MBP15,2... I saw that some people with Razer Blade 15 guide using MBP15,2 SMBIOS and I relized that's the problem you're facing. Not the USBMap.kext or USBPort.kext problem, I've tried any way but it's just work with MBP15,2 SMBIOS...

**Comment by doanhxd** [comment]
我将Razer Blade 15 Advanced model 2018与SMBIOS MacbookPro15,2一起使用...当我尝试使用除15,2以外的其他SMBIOS ... TB3（typeC）端口不再起作用...当我尝试插入时在Type C到HDMI（使用我的分立显示器）电缆中，除非您改回MBP15,2，否则它将无法工作。我认为您的TB3端口问题正在使用MBP15,2以外的其他SMBIOS。 ..我看到一些人使用MBP15,2 SMBIOS Razer Blade 15指南，我认为这是您面临的问题。这不是USBMap.kext或USBPort.kext问题，我尝试了任何方法，但仅适用于MBP15,2 SMBIOS ...

**Comment by tyson-hu** [comment]
Thanks for the suggestion! I gonna change it later and test, wish it would work!  <3

**Comment by tyson-hu** [comment]
by the way, nxt time u could just use English xd. I could understand this. 😊
