### ISSUE TITLE
I have a few questions please

### ISSUE THREAD

**Issue by Newfiejudd** [Mother-FKR/RazerBlade15-Base-Model-Hackintosh#3]
I have a few questions on your EFI configs. 
- What is the purpose of VerbStub.kext?
- Why are you using -hbfxbeta in the boot args. 

Thanks again for keeping this repo active. It's a wealth of information. 

Cheers

**Comment by tyson-hu** [comment]
- The purpose for `VerbStub` is make sure headphone work, but seems not really work on it. So yep, I think you cloud delete it.
- The reason that why I use  `-hbfxbeta` is make sure hibernation work on bigsur. but that's long time ago, I never test it without this boot args, you could try it :)

**Comment by tyson-hu** [comment]
In addition, I just test it, you cloud now delete both `-hbfxbeta` and `-brcmfxbeta`.
