### ISSUE TITLE
你好 请问 灵刃15在做了黑苹果之后续航时间大概是多久

### ISSUE THREAD

**Issue by ZergeMa** [Mother-FKR/RazerBlade15-Base-Model-Hackintosh#4]

**Comment by tyson-hu** [comment]
emmmm，这得看你电池的寿命还有你怎么使用了。大型软件和游戏我没试过，毕竟不插电多少会掉帧。日常使用的话（视频+聊天+码字）可以用四个多小时。一般比Windows多个半小时吧，反正在续航这方面就不要想太美好了。

**Comment by ZergeMa** [comment]
非常感谢  那这么看的话低分辨率还是有助于提高续航 打算买精英版 它多出的电池容量应该也能相应的提高一些续航 期待能有5个小时
