### ISSUE TITLE
Razer Blade 15 advance model 2018音频无法工作

### ISSUE THREAD

**Issue by liyawolf** [Mother-FKR/RazerBlade15-Base-Model-Hackintosh#7]
在使用你的EFI folder， big sur在我的Razer Blade 15 advance model 2018上显示不可用。现在我只能用蓝牙耳机使用音频。不知道兄弟有没有什么建议，谢谢了
![Screen Shot 2020-11-24 at 2 17 01 PM](https://user-images.githubusercontent.com/74986718/100141009-b9dd7000-2e5f-11eb-8348-f1ffa26c83a5.png)

**Comment by tyson-hu** [comment]
去把alcid改成13,多半是AppleALC的问题😗

**Comment by liyawolf** [comment]
谢谢指点！ 我是个新手，只会套用人家最好的efi。。。方便帮我改一下然后发到我的邮箱里吗？

**Comment by liyawolf** [comment]
另外用户doanhmaple 有给advanced
model的efi，里面的音频是工作的，但是屏幕不能调节亮度，只能最大，好像他不怎么回复issue。你可以看看他的配置文件

**Comment by tyson-hu** [comment]
就是因为他config里面的alcid设的是13所以我才会跟你这么说，而13在我电脑上只会检测到扬声器，所以我改成了23。由于我电脑现在不在我身边，我也没法直接教你怎么改。而至于他屏幕亮度的问题应该出在acpi上。

**Comment by liyawolf** [comment]
我用OCC把alcid改成了13，保存退出再重启，结果声音有显示出来，但是放YouTube还是喇叭没有声音出来，mic也没有检测到声音。
![Screen Shot 2020-11-24 at 11 55 58 PM](https://user-images.githubusercontent.com/74986718/100184932-9abafe80-2eb0-11eb-9279-53ca1a84194d.png)

当我插入耳机的时候，可以听到很多杂音的视频声音，
![Screen Shot 2020-11-25 at 12 08 48 AM](https://user-images.githubusercontent.com/74986718/100185745-98f23a80-2eb2-11eb-9870-be578814f013.png)


我还可以怎样试试呢？

**Comment by tyson-hu** [comment]
你试试冷重启（关机后等几秒再开机），我从Windows重启到macos也会这样，目前好像没啥解决办法。

**Comment by liyawolf** [comment]
我还是用上了doanhmaple的EFI，只是把你的屏幕亮度调节的文件替换掉了他的，结果屏幕就可以调节亮度了。加上他的音频是工作的，所以我的advance款终于完美了。非常感谢你的热心帮助，期待你的持续更新！

**Comment by tyson-hu** [comment]
没事，能用上就🉑️，更何况我其实也没帮到你什么🥲
