### ISSUE TITLE
DW1560 只用 AirportBrcmFixup.kext？？？

### ISSUE THREAD

**Issue by evenlee** [Mother-FKR/RazerBlade15-Base-Model-Hackintosh#9]
我的蓝牙和楼主同型号，但是突然灰色不能用了，开机提示 time out 20702A0 错误，我之前用的
BrcmBluetoohInjector
BrcmFirmwareData
BrcmatchRAM3
AirportBrcmFixup，
我试着用您的配置，只用一个AirportBrcmFixup，系统设置直接没有蓝牙图标，系统报告里面直接提示没有蓝牙，请问其他地方还需要配置吗？

**Comment by tyson-hu** [comment]
至少我是没什么问题😢
如果你蓝牙有问题就把`BrcmBluetoothInjector.kext`
`BrcmFirmwareData.kext`
`BrcmPatchRAM3.kext`
都装上吧。关于`airportbrcmfixup`记得把
`AirportBrcmFixup.kext/Contents/PlugInsAirPortBrcm4360_Injector.kext`这个plugin删除，只保留`AirPortBrcmNIC_Injector.kext`即可

**Comment by evenlee** [comment]
我用其他的kext以后蓝牙好了，但是只用AirportBrcmFixup确实不行。另外我的是b550i的板子，升级了最新的bios好的，好像和usb有关，非常感谢回复
